name: wifidrop
title: WIFIDrop
version: git
summary: Local peer-to-peer file transfer via WIFI.
description: |
  Run with:-
    $ wifidrop

website: https://wifidrop.js.org
contact: https://github.com/nuzulul/wifidrop/issues
issues: https://github.com/nuzulul/wifidrop/issues
source-code: https://github.com/nuzulul/wifidrop
license: GPL-3.0
icon: snap/wifidrop.png

confinement: strict
base: core22
grade: stable

apps:
  wifidrop:
    command: bin/wifidrop
    extensions: [gnome]
    plugs:
    - home
    - desktop
    - desktop-legacy
    - x11
    - unity7
    - wayland
    - browser-support
    - network
    - gsettings
    - pulseaudio
    - opengl
    - network-bind    
    environment:
      TMPDIR: $XDG_RUNTIME_DIR    

parts:
  wifidrop:
    plugin: dump
    source: snap/local
    source-type: local
    stage-snaps:
      - chromium/latest/stable  
    override-prime: |
      
      # Fix resource permissions
      chmod +rx $CRAFT_STAGE/bin/wifidrop

      snapcraftctl prime      