name: wifidrop
version: git
summary: Local peer-to-peer file transfer via WIFI.
description: |
  Run with:-
    $ wifidrop

confinement: devmode
base: core22

apps:
  wifidrop:
    command: bin/wifidrop

parts:
  wifidrop:
    plugin: npm
    npm-include-node: true
    npm-node-version: 22.16.0
    source: .